version: '3.5'
services:
  app:
    container_name: angular-crash-course
    build: ./
    networks:
      - my-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4200:4200'
networks:
  my-network:
    driver: bridge